os:
  editCommand: 'toggleterm'

keybinding:
  universal:
    return: '<c-\>'

gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
  showIcons: true
  sidePanelWidth: 0.2

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  diffContextSize: 10
  increaseContextInDiffView: '}'
  decreaseContextInDiffView: '{'
