os:
  editCommand: 'toggleterm'

keybinding:
  universal:
    return: '<c-\>'

gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
  showIcons: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
